name: "Default test"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --tag test:latest .
    - id: scan
      name: Scan Image
      uses: anchore/scan-action@v1.0.1
      with:
        image-reference: "test:latest"
        fail-build: true
        #debug: true
        custom-policy-path: .anchore_fail_always.json
        #anchore-version: v0.5.2
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: content
        path: ${{ steps.scan.outputs.billofmaterials }}
        

